---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAnl9GQHsIr+fRj0UQpaYHkg6KLFCUD3Cz74XGl0fTSq5kT6ERXMyWMAIZHZ43kIbXmSttdbE6yrcM+blTlNmvqlJ8jZ+jnmfu5Nb5jPfg5cdFhKWD2GwMNN7W5BDd1qq9buyFM4RNXRMgBQ01b9OyhwgmeuEvMlsS0qTN20RrIHktExSDwYPXqDQw+UfOaMsPEvcBb8xRUBGHHRlXZNo8+/5nFEVicHyEiCO4JvFxVhigLhB5lJBnh66jTEk+PlaC85Cxw0BY3nYwYpu8cxdtQZHFOUcNUN1Ug06TEcJGlhHRKEi0D1IK6jn2eQ7I1MgrNnGlz/6IKjdkyXx1pmsTwJYK6Bxapw0sdPfPl3CkMvs1MnB0TdQ8VnPDBzjD3286QGtPLLVagdHSEiM8bX5UT6VIKHn5+3xlLvWbVvT+BYVLx8dH+YbMZ93qJiJumoND9Ea6vTSYVCr0OAEch8Dmk7hDyFAVGQIwEHBPders2ozbQbQUrKaemc96PmmkG+nuZ2t+dVGks3sUiMKu+1YDB5QerrEmQ4Imi5G/fj3uhIbHKKAHPrcOf5OadL2WGnr8u1ry3yP0gYostxmKMNuwdgs4qDIxCyFoCJsDGB9HQoFTlIkp8mbHxQA4ln4Rl+q/rUk98W9HndAhLXgKT/07gc91O6FgDONGHZvE2EUdW+zf0ldYyA7aS+c5wlQDeEui+ZFD3FkZVwBP2aTZvtltvbxybkZ/8Qo42tKSs72oXb/so9b04o68MAl1/Ld2feY2N4J5sXHxVQhACzylC+Vx0pXf32t/i3m21nZhkjr01flQhcHggUvZ6Ba81DyDE/14N00/0r2HZ//NSs5oY1U89Ju6AJNcWNj5rbJU+IVFaLiI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson
