apiVersion: nsvijay04b1.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.nsvijay04b1.io
spec:
  project: production
  source:
    path: charts/argo-workflows
    repoURL: https://github.com/nsvijay04b1/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        server: 
          ingress:
            hosts:
              - argo-workflows.localhost
            enabled: true
            ingressClassName: nginx
        controller:
          containerRuntimeExecutor: emissary
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

